### ISSUE TITLE
Distributed  fluid NMT error

### ISSUE THREAD

**Issue by gongweibao** [gongweibao/tests#2]
```
4215 Traceback (most recent call last):
4216   File "nmt_fluid.py", line 336, in <module>
4217     main()
4218   File "nmt_fluid.py", line 324, in main
4219     train_loop(exe, trainer_prog)
4220   File "nmt_fluid.py", line 227, in train_loop
4221     use_program_cache=True)
4222   File "/paddle/python/paddle/fluid/executor.py", line 323, in run
4223     fetch_var_name=fetch_var_name)
4224   File "/paddle/python/paddle/fluid/executor.py", line 232, in _add_feed_fetch_ops
4225     out = global_block.var(name)
4226   File "/paddle/python/paddle/fluid/framework.py", line 708, in var
4227     raise ValueError("var %s not in this block" % name)
4228 ValueError: var ^A^@^@^@^@^@^@^@0??^C^@^@^@^@p^Y?@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@0??^C^@^@^@^@? not in this block
```

**Comment by gongweibao** [comment]
```
```
*** Aborted at 1522660627 (unix time) try "date -d @1522660627" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x16342) received by PID 23716 (TID 0x7ff0e8855700) from PID 90946; stack trace: ***
    @     0x7ff0e8230390 (unknown)
    @     0x7ff0e7ef4840 (unknown)
    @     0x7ff0ae491221 std::__cxx11::basic_string<>::_M_construct<>()
    @     0x7ff0ae492691 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind11BindVarDsecERNS_6moduleEEUlRNS2_9framework7VarDescEE_NS_5bytesEJS8_EJNS_4nameENS_9is_methodENS_7siblingENS_19return_value_policyEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESS_
    @     0x7ff0ae45a4e4 pybind11::cpp_function::dispatcher()
    @           0x4c37ed PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4a5371 PyObject_CallFunction
    @           0x41cdd7 _PyObject_GenericGetAttrWithDict
    @           0x4bc24b PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4eb30f (unknown)
    @           0x4e5422 PyRun_FileExFlags
    @           0x4e3cd6 PyRun_SimpleFileExFlags
    @           0x493ae2 Py_Main
    @     0x7ff0e7e75830 __libc_start_main
    @           0x4933e9 _start
    @                0x0 (unknown)
Segmentation fault
```
```

**Comment by gongweibao** [comment]
```
1154 Traceback (most recent call last):
1155   File "nmt_fluid.py", line 348, in <module>
1156     main()
1157   File "nmt_fluid.py", line 336, in main
1158     train_loop(exe, trainer_prog)
1159   File "nmt_fluid.py", line 228, in train_loop
1160     lr_scheduler.update_learning_rate(data_input)
1161   File "/root/go/src/github.com/PaddlePaddle/models/fluid/neural_machine_translation/transformer/optim.py", line 41, in update_learning_rate
1162     print("learning_rate_name:", self.learning_rate.name)
1163   File "/paddle/python/paddle/fluid/framework.py", line 285, in name
1164     return self.desc.name()
1165 MemoryError: std::bad_alloc
```
